# Generated by Django 3.0.6 on 2020-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
